services:
  - type: web
    name: soori-academy-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PASSWORD
        value: soori2024
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false